---
title: Stl Lead Inequity
output: html_document
editor_options: 
  chunk_output_type: console
---
  
## load libraries
```{r}
library(tidyverse)
library(janitor)
```

## import and clean data
```{r}
stl_lead <- read_csv(here::here("data", "stl_blood_lead.csv"))
stl_lead <- clean_names(stl_lead)
```

## explore data
```{r}
skimr::skim(stl_lead)
dim(stl_lead)
```

## create new variable
```{r}
stl_lead_prop <- dplyr::mutate(.data = stl_lead, prop_white = ((stl_lead$white / stl_lead$total_pop)*100))
```

## visualize data
```{r}
#| fig-cap: "This scatterplot shows a general trend of higher white populations have a lower level of percent blood lead elevate"
ggplot(data = stl_lead_prop,
       aes(x = pct_elevated, y = prop_white)) +
         geom_point(color = "red", alpha = 0.5, size = 1.4) +
  theme_minimal() +
  labs(title = "Percent of elevated blood lead levels in children vs. percent of population white", x = "Percent blood lead elevated", y = "Percent of population white")
```

## save plot
```{r}
ggsave(here::here("figs", "stl_lead_plot.png"), height = 6, width = 5)
```

## create histogram
```{r}
ggplot(data = stl_lead, aes(x = pct_elevated)) +
  geom_histogram(color = "purple", fill = "pink") +
  theme_minimal() +
  labs (title = "Amount of Percent Blood Lead Level Elevated", x = "Percent Blood Level Elevated", y = "Count" )
```

## save histogram
```{r}
ggsave(here::here("figs", "stl_lead_histogram.png"), height = 6, width = 5)
```

